version: "3"

services:
  serverapp:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: server
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: